import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Sora, Space_Grotesk } from 'next/font/google';

import './globals.css';
import BackgroundImage from '@/components/common/background-image';
import { Providers } from '@/components/common/providers';

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  display: 'swap',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'slapshot.club',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${sora.variable} ${spaceGrotesk.variable}`}>
      <NextIntlClientProvider messages={messages}>
        <Providers>
          <body className="bg-background text-foreground relative min-h-screen font-sans antialiased">
            <BackgroundImage />
            {children}
          </body>
        </Providers>
      </NextIntlClientProvider>
    </html>
  );
}
